### Get list all actors (default pagination)
GET http://localhost:5000/api/actors HTTP/1.1

### Get list all actors (custom pagination)
GET http://localhost:5000/api/actors?page=1&limit=10 HTTP/1.1

### Get actor by ID
GET http://localhost:5000/api/actors/3 HTTP/1.1

### Add actor
POST http://localhost:5000/api/actors HTTP/1.1
content-type: application/json

{
  "fullName": "New actor",
  "country": "United States of America",
  "birthDate": "2000-01-01",
  "deathDate": "",
  "photo": "",
  "biography": ""
}

### Edit actor by ID
PATCH http://localhost:5000/api/actors/238 HTTP/1.1
content-type: application/json

{
  "fullName": "Updated actor",
  "country": "",
  "birthDate": "",
  "deathDate": "",
  "photo": "",
  "biography": ""
}

### Remove actor by ID
DELETE  http://localhost:5000/api/actors/238 HTTP/1.1
