### Get list all directors (default pagination)
GET http://localhost:5000/api/directors HTTP/1.1

### Get list all directors (custom pagination)
GET http://localhost:5000/api/directors?page=1&limit=10 HTTP/1.1

### Get director by ID
GET http://localhost:5000/api/directors/3 HTTP/1.1

### Add director
POST http://localhost:5000/api/directors HTTP/1.1
content-type: application/json

{
  "fullName": "New director",
  "country": "United States of America",
  "birthDate": "16 April 2025",
  "deathDate": "",
  "photo": "",
  "biography": ""
}

### Edit director by ID
PATCH http://localhost:5000/api/directors/29 HTTP/1.1
content-type: application/json

{
  "fullName": "Updated director",
  "country": "",
  "birthDate": "",
  "deathDate": "",
  "photo": "",
  "biography": ""
}

### Remove director by ID
DELETE  http://localhost:5000/api/directors/29 HTTP/1.1
