### Get list all genres (default pagination)
GET http://localhost:5000/api/genres HTTP/1.1

### Get list all genres (custom pagination)
GET http://localhost:5000/api/genres?page=1&limit=10 HTTP/1.1

### Get genre by id
GET http://localhost:5000/api/genres/3 HTTP/1.1

### Add genre
POST http://localhost:5000/api/genres HTTP/1.1
content-type: application/json

{
  "title": "New genre",
  "logo": ""
}

### Edit genre by id
PATCH http://localhost:5000/api/genres/20 HTTP/1.1
content-type: application/json

{
  "title": "Updated genre",
  "logo": ""
}

### Remove genre by id
DELETE  http://localhost:5000/api/genres/20 HTTP/1.1
