### Get list all locations (default pagination)
GET http://localhost:5000/api/locations HTTP/1.1

### Get list all locations (custom pagination)
GET http://localhost:5000/api/locations?page=1&limit=5 HTTP/1.1

### Get location by id
GET http://localhost:5000/api/locations/3 HTTP/1.1

### Add location
POST http://localhost:5000/api/locations HTTP/1.1
content-type: application/json

{
  "title": "New location",
  "country": "United States of America",
  "coatOfArms": ""
}

### Edit location by id
PATCH http://localhost:5000/api/locations/11 HTTP/1.1
content-type: application/json

{
  "title": "Updated location",
  "country": "",
  "coatOfArms": ""
}

### Remove location by id
DELETE  http://localhost:5000/api/locations/11 HTTP/1.1
