### Get list all locations (default pagination)
GET http://localhost:5000/api/locations HTTP/1.1
Content-Type: application/json

### Get list all locations (custom pagination)
GET http://localhost:5000/api/locations?page=1&limit=8 HTTP/1.1
Content-Type: application/json

### Add location
POST http://localhost:5000/api/locations HTTP/1.1
Content-Type: application/json

{
  "title": "New location",
  "country": "United States of America",
  "coatOfArms": ""
}

### Get location by UUID
GET http://localhost:5000/api/locations/68de446d-938a-4c93-bd1f-39b5e602bfbc HTTP/1.1
Content-Type: application/json

### Edit location by UUID
PATCH http://localhost:5000/api/locations/68de446d-938a-4c93-bd1f-39b5e602bfbc HTTP/1.1
Content-Type: application/json

{
  "title": "Updated location",
  "country": "",
  "coatOfArms": ""
}

### Remove location by UUID
DELETE  http://localhost:5000/api/locations/68de446d-938a-4c93-bd1f-39b5e602bfbc HTTP/1.1
Content-Type: application/json
